# Generated by Django 5.0.2 on 2024-03-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_facility',
        ),
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_facility', models.CharField(max_length=250)),
                ('hotel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.hotel')),
            ],
        ),
    ]
