# Generated by Django 5.0.6 on 2024-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='room_facility',
            field=models.JSONField(default=dict),
        ),
    ]
