# Generated by Django 5.0.2 on 2024-03-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_remove_hotel_hotel_facility_hotelfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfacility',
            name='hotel_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.hotel'),
        ),
    ]
