# Generated by Django 5.0.2 on 2024-03-04 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_hotelimages_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
    ]
