# Generated by Django 5.0.2 on 2024-03-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_alter_hotelimages_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catogory', to='Hotel.catagories'),
        ),
        migrations.AlterField(
            model_name='hotelfacility',
            name='hotel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Hotel_facility', to='Hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelreviews',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Hotel.customer'),
        ),
    ]
