# Generated by Django 5.0.2 on 2024-03-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_alter_hotel_hotel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='Hotel.catagories'),
        ),
        migrations.AlterField(
            model_name='hotelfacility',
            name='hotel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility', to='Hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelreviews',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Hotel.hotel'),
        ),
    ]
