# Generated by Django 5.0.2 on 2024-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_hotel_hotel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
