# Generated by Django 5.0.2 on 2024-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_alter_hotelimages_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel_image',
            field=models.FileField(upload_to='media'),
        ),
    ]
